# Generated by Django 4.2.11 on 2024-04-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_remove_choice_choice_text_choice_choice1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="choice1",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice2",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice3",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice4",
        ),
        migrations.AddField(
            model_name="choice",
            name="choice_type",
            field=models.CharField(
                choices=[
                    ("CHOICE1", "Choice1"),
                    ("CHOICE2", "Choice2"),
                    ("CHOICE3", "Choice3"),
                    ("CHOICE4", "Choice4"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
