# Generated by Django 4.2.11 on 2024-04-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_remove_choice_choice_type_remove_vote_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="title",
            field=models.CharField(default="", max_length=30),
        ),
    ]
