# Generated by Django 4.2.11 on 2024-04-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_poll_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="choice1",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="poll",
            name="choice2",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="poll",
            name="choice3",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="poll",
            name="choice4",
            field=models.CharField(default="", max_length=50),
        ),
    ]
