# Generated by Django 4.2.11 on 2024-04-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0006_poll_choice1_poll_choice2_poll_choice3_poll_choice4"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="choice_type",
        ),
        migrations.AddField(
            model_name="vote",
            name="choice",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
